version: "3.8"

services:
  node-1:
    build: ./ai-node
    container_name: node-1
    volumes:
      - shared-data:/app/shared
    depends_on:
      - blockchain-node
    environment:
      - NODE_ID=1
    networks:
      - blockchain_network

  node-2:
    build: ./ai-node
    container_name: node-2
    volumes:
      - shared-data:/app/shared
    depends_on:
      - blockchain-node
    environment:
      - NODE_ID=2
    networks:
      - blockchain_network

  node-3:
    build: ./ai-node
    container_name: node-3
    volumes:
      - shared-data:/app/shared
    depends_on:
      - blockchain-node
    environment:
      - NODE_ID=3
    networks:
      - blockchain_network

  blockchain-node:
    build: ./blockchain-node
    container_name: blockchain-node
    volumes:
      - shared-data:/app/shared
    environment:
      - BLOCKCHAIN_PORT=5002
    networks:
      - blockchain_network

volumes:
  shared-data:

networks:
  blockchain_network:
    driver: bridge
